name: iOS 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: "Lint "
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.1.0.app

      - name: Linting
        run: make clean-ios analyze-ios

  test:
    name: "Test & Report "
    runs-on: macos-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.1.0.app

      - name: Test
        run: make clean-ios test-ios report-ios

      - name: Report
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: iOS
          files: ./build/reports/ios/coverage.json

  build:
    name: "Build "
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.1.0.app

      - name: Build
        run: make clean-ios build-ios
